language: python
python: 
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - python server.py

deploy:
  provide: azure_web_apps
  username: sawoodrocket@gmail.com
  password: 20harris40
  site: apiavocets
